### ISSUE TITLE
Initialize or stop checking for conf file when createtemp is set

### ISSUE THREAD

**Issue by shyba** [lbryio/lbcwallet#2]
On SDK tests we set `createtemp` and `appdata` but lbcwallet still goes to the home directory and tries to find a conf file.
I then tried setting `configfile`, but it ignored and went again to the home directory.
```
2021-11-12 20:24:15,416 - lbry.wallet.orchstr8.node.lbcwallet - INFO - Error creating a default config file: open /home/runner/.lbcwallet/lbcwallet.conf: no such file or directory
```

Interestingly, when I touched the file at the location I set on `configfile`, it stopped ignoring and worked flawlessly.

**Comment by roylee17** [comment]
`lbcctl` was trying to create a `lbcctl.conf` for itself by copying the `rpcuser` and `rpcpass` settings from either a `lbcd.conf` (or `lbcwallet.conf` when `--wallet` was set) from default application folder (on linux: home directory).

This should be a warning instead of an error. In the `lbry-sdk` testcases, we explicitly specify `rpcuser/rpcpass` for both the RPC server (lbcwallet) and client (lbcctl), so the RPC calls should work despite the config warning.

**Comment by shyba** [comment]
This can probably be closed. It is being logged correctly and we identified some other issue on the python side of the script that originated the issue.
